String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'chocolate mint crunch',
    '%4'                    : 'carrot',
    '%8'                    : 'lavender earl grey',
    '%16'                   : 'strawberry lava fudge',
    '%32'                   : 'vanilla bat',
    '%64'                   : 'pink rose',
    '%128'                  : 'lemon blossom',
    '%256'                  : 'blueberry cheesecake',
    '%512'                  : 'salted caramel chocolate chip',
    '%1024'                 : 'butterscotch waffle cone',
    '%2048'                 : 'PBJ',
    '%4096'                 : '2022 Confetti Vanilla',
    '%8192'                 : 'Unicorn',
    '%p0'                   : 'chocolate mint crunch',
    '%p4'                   : 'carrot',
    '%p8'                   : 'lavender earl grey',
    '%p16'                  : 'strawberry lava fudge',
    '%p32'                  : 'vanilla bat',
    '%p64'                  : 'pink rose',
    '%p128'                 : 'lemon blossom',
    '%p256'                 : 'blueberry cheesecake',
    '%p512'                 : 'salted caramel choc. chip',
    '%p1024'                : 'butterscoth waffle cone',
    '%p2048'                : 'PBJ',
    '%p4096'                : '2022 Confetti Vanilla',
    '%p8192'                : 'Unicorn'

	},

  "en": {
    "%game-intro"           : "Join the <strong>Cupcakes!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
    "%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-CUPCAKES #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'chocolate mint crunch',
    '%4'                    : 'carrot',
    '%8'                    : 'lavender earl grey',
    '%16'                   : 'strawberry lava fudge',
    '%32'                   : 'vanilla bat',
    '%64'                   : 'pink rose',
    '%128'                  : 'lemon blossom',
    '%256'                  : 'blueberry cheesecake',
    '%512'                  : 'salted caramel chocolate chip',
    '%1024'                 : 'butterscotch waffle cone',
    '%2048'                 : 'PBJ',
    '%4096'                 : '2022 Confetti Vanilla',
    '%8192'                 : 'Unicorn',
    '%p0'                   : 'chocolate mint crunch',
    '%p4'                   : 'carrot',
    '%p8'                   : 'lavender earl grey',
    '%p16'                  : 'strawberry lava fudge',
    '%p32'                  : 'vanilla bat',
    '%p64'                  : 'pink rose',
    '%p128'                 : 'lemon blossom',
    '%p256'                 : 'blueberry cheesecake',
    '%p512'                 : 'salted caramel choc. chip',
    '%p1024'                : 'butterscotch waffle cone',
    '%p2048'                : 'PBJ',
    '%p4096'                : '2022 Confetti Vanilla',
    '%p8192'                : 'Unicorn'
  }

});
